project: 
  type: website
  output-dir: docs

website: 
  page-navigation: true
  title: "Leobardo Oscar Alcantara Oca√±a" 
  site-url: "https://nmfs-opensci.github.io/NOAA-quarto-simple" 
  repo-url: "https://github.com/nmfs-opensci/NOAA-quarto-simple"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "2026 &copy; CC-1.0 Leobardo Oscar Ocana"
  
  sidebar:
    background: "#D9E3E4"
    logo: ""
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://linktr.ee/leobardo_oscar
        text: "Linktree"
      - icon: github
        href: https://github.com/leobardooscar
        text: "GitHub"
      - icon: x
        href: https://x.com/joshua_w_d
        
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/continuing_education.qmd
        text: Further Education
      - href: content/project_gallery.qmd
        text: Project Gallery
      - href: content/about_me.qmd
        text: About me
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
